# Generated by Django 5.2.6 on 2025-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacao',
            name='numero_processo',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
