# Generated by Django 5.2.6 on 2025-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0002_alter_licitacao_numero_processo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='licitacao',
            name='data_homologacao',
        ),
        migrations.AddField(
            model_name='licitacao',
            name='status',
            field=models.CharField(choices=[('digitalizado', 'Digitalizado'), ('em andamento', 'Em Andamento'), ('homologado', 'Homologado'), ('publicado', 'Publicado'), ('rascunho', 'Rascunho'), ('recurso', 'Recurso'), ('concuido', 'Concluído')], default='rascunho', max_length=20),
        ),
    ]
