# Generated by Django 5.2.6 on 2025-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0003_fornecedores_remove_licitacao_data_homologacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='data_de_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='data_de_homologacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em Andamento'), ('publicado', 'Publicado'), ('rascunho', 'Rascunho'), ('recurso', 'Recurso'), ('concuido', 'Concluído'), ('digitalizado', 'Digitalizado'), ('homologado', 'Homologado')], default='rascunho', max_length=20),
        ),
    ]
