# Generated by Django 5.2.7 on 2025-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0004_licitacao_data_de_abertura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='licitacao',
            options={'verbose_name_plural': 'Licitações'},
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('digitalizado', 'Digitalizado'), ('concuido', 'Concluído'), ('rascunho', 'Rascunho'), ('homologado', 'Homologado'), ('recurso', 'Recurso'), ('em andamento', 'Em Andamento')], default='rascunho', max_length=20),
        ),
    ]
