# Generated by Django 5.2.7 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0005_alter_fornecedores_options_alter_licitacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='fornecedores_vencedores',
            field=models.ManyToManyField(blank=True, to='licitacoes.fornecedores', verbose_name='Vencedores do Processo'),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('recurso', 'Recurso'), ('digitalizado', 'Digitalizado'), ('homologado', 'Homologado'), ('em andamento', 'Em Andamento'), ('concuido', 'Concluído')], default='rascunho', max_length=20),
        ),
    ]
